sudo: false
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
matrix:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/rails60.gemfile
  - rvm: 2.3
    gemfile: gemfiles/rails61.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails60.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails61.gemfile
  - rvm: 2.7
    gemfile: gemfiles/rails42.gemfile
  - rvm: 3.0
    gemfile: gemfiles/rails42.gemfile
  - rvm: 3.0
    gemfile: gemfiles/rails50.gemfile
  - rvm: 3.0
    gemfile: gemfiles/rails51.gemfile
  - rvm: 3.0
    gemfile: gemfiles/rails52.gemfile
script:
  - bundle exec rspec
