sudo: false
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
script: bundle exec rspec
