sudo: false
language: ruby
rvm:
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
before_install:
  - gem install bundler -v 1.15.3
script: bundle exec rspec
