name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, 3.3, 3.4]
        gemfile: ['rails42', 'rails50', 'rails51', 'rails52', 'rails60', 'rails61', 'rails70', 'rails71', 'rails72', 'rails80']
        exclude:
          - ruby: 2.3
            gemfile: rails60
          - ruby: 2.3
            gemfile: rails61
          - ruby: 2.3
            gemfile: rails70
          - ruby: 2.3
            gemfile: rails71
          - ruby: 2.3
            gemfile: rails72
          - ruby: 2.3
            gemfile: rails80
          - ruby: 2.4
            gemfile: rails60
          - ruby: 2.4
            gemfile: rails61
          - ruby: 2.4
            gemfile: rails70
          - ruby: 2.4
            gemfile: rails71
          - ruby: 2.4
            gemfile: rails72
          - ruby: 2.4
            gemfile: rails80
          - ruby: 2.5
            gemfile: rails70
          - ruby: 2.5
            gemfile: rails71
          - ruby: 2.5
            gemfile: rails72
          - ruby: 2.5
            gemfile: rails80
          - ruby: 2.6
            gemfile: rails70
          - ruby: 2.6
            gemfile: rails71
          - ruby: 2.6
            gemfile: rails72
          - ruby: 2.6
            gemfile: rails80
          - ruby: 2.7
            gemfile: rails42
          - ruby: 2.7
            gemfile: rails72
          - ruby: 2.7
            gemfile: rails80
          - ruby: 3.0
            gemfile: rails42
          - ruby: 3.0
            gemfile: rails50
          - ruby: 3.0
            gemfile: rails51
          - ruby: 3.0
            gemfile: rails52
          - ruby: 3.0
            gemfile: rails72
          - ruby: 3.0
            gemfile: rails80
          - ruby: 3.1
            gemfile: rails42
          - ruby: 3.1
            gemfile: rails50
          - ruby: 3.1
            gemfile: rails51
          - ruby: 3.1
            gemfile: rails52
          - ruby: 3.1
            gemfile: rails80
          - ruby: 3.2
            gemfile: rails42
          - ruby: 3.2
            gemfile: rails50
          - ruby: 3.2
            gemfile: rails51
          - ruby: 3.2
            gemfile: rails52
          - ruby: 3.3
            gemfile: rails42
          - ruby: 3.3
            gemfile: rails50
          - ruby: 3.3
            gemfile: rails51
          - ruby: 3.3
            gemfile: rails52
          - ruby: 3.4
            gemfile: rails42
          - ruby: 3.4
            gemfile: rails50
          - ruby: 3.4
            gemfile: rails51
          - ruby: 3.4
            gemfile: rails52

    name: ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Bundle list
      run: |
        bundle list
    - name: Run test
      run: |
        bundle exec rspec
